[target.xtensa-esp32-none-elf]
# runner = "espflash flash --monitor --chip esp32 --flash-freq 40mhz --flash-mode dio --port /dev/tty.usbserial-54350025201 --log-format defmt"
runner = "espflash flash --monitor --chip esp32 --flash-freq 40mhz --flash-size 4mb --flash-mode dio --port /dev/tty.usbserial-11103"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"


[env]
ESP_LOG = "info"

# Xtensa only:
# Needed for nightly, until llvm upstream has support for Rust Xtensa.
[unstable]
build-std = ["alloc", "core"]